services:
  - type: web
    name: harvestify
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential cython
      pip install -r requirements.txt
    startCommand: gunicorn app:app
